### PR TITLE
Add TypeScript

### PR DESCRIPTION
**Pull request by dongle-the-gadget**

### CODE REVIEW

**Comment by SapphireDisD** [comment]
Why is useRef added?

**Comment by dongle-the-gadget** [comment]
I used to use it but then forgot to remove it.

**Comment by SapphireDisD** [comment]
Wait a second...

**Comment by dongle-the-gadget** [comment]
Deleted that unused useRef.

**Comment by SapphireDisD** [comment]
Oh, thank you.

**Comment by SapphireDisD** [comment]
Merging...

**Pull request merged**
